version: '3.1'
services:
  stats-client:
    build: ewm_stats_service/client
    ports:
      - "9090:9090"
    depends_on:
      - stats-server
    environment:
      - EWM_STATS_SERVER_URL = http://stats-server:9091

  stats-server:
    build: ewm_stats_service/server
    ports:
      - "9091:9091"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin

  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=ewm_stats

  ewm-service:
    build: ewm_main_service
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
