server:
  port: 8080
  error:
    include-message: always
ewm-stats-server:
  url: http://localhost:9090
spring:
  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL10Dialect
      format_sql: true
      show_sql: true
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_main
    username: admin
    password: admin