--drop table compilation_events cascade;
--drop table compilations cascade;
--drop table requests cascade;
--drop table ratings cascade;
--drop table events cascade;
--drop table locations cascade;
--drop table categories cascade;
--drop table users cascade;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(128)                            NOT NULL,
    email VARCHAR(128) UNIQUE                     NOT NULL,
    CONSTRAINT users_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(128) UNIQUE                  NOT NULL,
    CONSTRAINT categories_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         VARCHAR(2048)                           NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    description        VARCHAR(7168)                           NOT NULL,
    created            TIMESTAMP                               NOT NULL,
    event_date         TIMESTAMP                               NOT NULL,
    published          TIMESTAMP,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  INT                                     NOT NULL,
    request_moderation BOOLEAN                                 NOT NULL,
    title              VARCHAR(128)                            NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    location_id        BIGINT                                  NOT NULL,
    state              VARCHAR(32)                             NOT NULL,
    CONSTRAINT events_pk PRIMARY KEY (id),
    CONSTRAINT events_users_null_fk FOREIGN KEY (initiator_id) REFERENCES users (id),
    CONSTRAINT events_categories_null_fk FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat FLOAT                                   NOT NULL,
    lon FLOAT                                   NOT NULL,
    CONSTRAINT locations_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS ratings
(
    event_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    rate     BIGINT NOT NULL,
    CONSTRAINT ratings_users_null_fk FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT ratings_events_null_fk FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status       VARCHAR(32)                             NOT NULL,
    created      TIMESTAMP                               NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    CONSTRAINT requests_pk PRIMARY KEY (id),
    CONSTRAINT requests_users_null_fk FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT requests_events_null_fk FOREIGN KEY (event_id) REFERENCES events (id)
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(128)                            NOT NULL,
    pinned BOOLEAN                                 NOT NULL,
    CONSTRAINT compilations_pk PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    CONSTRAINT compilation_events_null_fk FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT events_compilation_null_fk FOREIGN KEY (compilation_id) REFERENCES compilations (id)
);